### ISSUE TITLE
warning: a function declaration without a prototype is deprecated in all versions of C

### ISSUE THREAD

**Issue by MatthieuStigler** [MatthieuStigler/lfe#3]
CRAN team sent a message complaining about new CRAN CHECK errors, and threatening to remove the package by 2023-02-11 if unaddressed. 

> Dear maintainer,
> 
> Please see the problems shown on <https://cran.r-project.org/web/checks/check_results_lfe.html>.
> 
> Please correct before 2023-02-11 to safely retain your package on CRAN.
> 
> For further details see https://www.stats.ox.ac.uk/pub/bdr/sprintf.txt

Problems are:

> checking whether package ‘lfe’ can be installed ... WARNING
Found the following significant warnings:
  ./lfe.h:121:19: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
  ./lfe.h:122:13: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
  utils.c:195:19: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
  utils.c:208:13: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
See https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/lfe-00install.html for details.

and:

> checking compiled code ... WARNING
File ‘lfe/libs/lfe.so’:
  Found ‘__sprintf_chk’, possibly from ‘sprintf’ (C)
    Objects: ‘demean.o’, ‘kaczmarz.o’, ‘utils.o’
> Compiled code should not call entry points which might terminate R nor write to stdout/stderr instead of to the console, nor use Fortran I/O nor system RNGs nor [v]sprintf.
> See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.`

**Comment by pachadotdev** [comment]
hi @MatthieuStigler 
I have opened a PR that fixes this issue, but also applies proper indentation to the written code

**Comment by MatthieuStigler** [comment]
Was fixed by @pachadotdev , thanks a lot!!

**Comment by MatthieuStigler** [comment]
Just submitted and... unfortunately, it looks like the warning is still there? see https://win-builder.r-project.org/incoming_pretest/lfe_2.9-0_20230120_092248/Debian/00check.log

> ./lfe.h:115:19: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
  ./lfe.h:116:13: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
  utils.c:231:19: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
  utils.c:244:13: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]

**Comment by pachadotdev** [comment]
> Just submitted and... unfortunately, it looks like the warning is still there? see https://win-builder.r-project.org/incoming_pretest/lfe_2.9-0_20230120_092248/Debian/00check.log
> 
> > ./lfe.h:115:19: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
> > ./lfe.h:116:13: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
> > utils.c:231:19: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
> > utils.c:244:13: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]

that's a new warning, I'll try to bypass it in a new PR

**Comment by MatthieuStigler** [comment]
@pachadotdev , just submittd, and got rejected, but it seems we are getting closer! :-)

Now the message appears only for two lines:

> Found the following significant warnings:
  utils.c:231:19: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
  utils.c:244:13: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
See ‘/srv/hornik/tmp/CRAN/lfe.Rcheck/00install.out’ for details.

Do you think you could have a look? Thanks!

**Comment by pachadotdev** [comment]
> @pachadotdev , just submittd, and got rejected, but it seems we are getting closer! :-)
> 
> Now the message appears only for two lines:
> 
> > Found the following significant warnings:
> > utils.c:231:19: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
> > utils.c:244:13: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
> > See ‘/srv/hornik/tmp/CRAN/lfe.Rcheck/00install.out’ for details.
> 
> Do you think you could have a look? Thanks!

sure! it's the R user interruption, let me write a workaround

**Comment by pachadotdev** [comment]
@MatthieuStigler I've uploaded to RHub and Winbuilder to check if the error is gone

**Comment by MatthieuStigler** [comment]
Thanks! I see you made important non-technical changes to the DESCRIPTION file? I think it would be good to separate the technical commits from those, so that we can discuss them?

**Comment by pachadotdev** [comment]
> 

yes, let me revert those !!!!!!

**Comment by pachadotdev** [comment]
> Thanks! I see you made important non-technical changes to the DESCRIPTION file? I think it would be good to separate the technical commits from those, so that we can discuss them?

@MatthieuStigler Reverted!! I have my own branch where I added a Poisson GLM. Let's discuss that later.
